import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import AmplitudeInitializer from "@/components/AmplitudeInitializer";
import Providers from "@/components/Providers";
import SideBar from "@/components/SideBar";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Script
          src="https://cdn.amplitude.com/libs/analytics-browser-2.11.9-min.js.gz"
          strategy="afterInteractive"
        />
        <AmplitudeInitializer />
        <Providers>
          <Suspense fallback={null}>
            <SideBar
              links={[
                { label: "Inicio", href: "/" },
                { label: "Catálogo", href: "/#catalog" },
                { label: "Acerca", href: "/#about" },
                { label: "FAQ", href: "/faq" },
                { label: "Safety", href: "/safety" },
              ]}
            />
          </Suspense>
          <div className="min-h-screen md:pl-[calc(18rem+1rem)]">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
